### ISSUE TITLE
Implications of the hook-related warning thrown when using Opacus

### ISSUE THREAD

**Issue by HarrisonWilde** [nhsx/NHSSynth#38]
Under (I think) all circumstances when using Opacus to wrap a VAE or GAN architecture, we get the following warning:

```
Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated
and will be removed in future versions. This hook will be missing some grad_input. Please use
register_full_backward_hook to get the documented behavior.
```

I would like to track the information available here:

- Issue discussing it: https://github.com/pytorch/opacus/issues/328#issuecomment-1324550076
- PR fixing the issue? Will see when I can use pytorch 2.0 https://github.com/pytorch/opacus/pull/581
- "Warning can be ignored": https://discuss.pytorch.org/t/arbitrary-batch-sizes-after-passing-dataloader-through-privacy-engine/161632/4
- "Somewhat expected": https://discuss.pytorch.org/t/deprecation-warning-with-latest-torch-and-opacus/127114

Note that I have tried forking Opacus and changing `grad_sample_module.py` to use `register_full_backward_hook` but the warning persists. I believe this should be resolved soon once we can move to PyTorch 2.0 (SDV currently blocking).

**Comment by HarrisonWilde** [comment]
Have had confirmation from Opacus' lead developer that this can be ignored, closing for now

**Comment by kr-ramesh** [comment]
Hi, I just wanted to clarify that the warning doesn't necessarily imply that the DP guarantee will be affected somehow, right (particularly if the modules can be validated by the validator & the grad_sample functions for each of the layers already exist in the library). I'd be grateful for any info regarding this, thank you!
